set_property PACKAGE_PIN A16 [get_ports a]
set_property PACKAGE_PIN A17 [get_ports b]
set_property PACKAGE_PIN A21 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
